[package]
name = "gpux-radix-color"
description = "GPUX Radix Colors"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gpui.workspace = true
anyhow.workspace = true

[lints]
workspace = true

[[example]]
name = "main"
path = "examples/main.rs"
