[package]
name = "gpux-nes-css"
description = "GPUX NES.css components"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gpui.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
gpux-css.workspace = true
rust-embed.workspace = true

[lints]
workspace = true

[[example]]
name = "logos"
path = "examples/logos.rs"
