// Copyright 2024 Phung Le Son.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/phungleson/gpux/blob/main/LICENSE-APACHE
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use gpui::{
    div, px, BoxShadow, ElementId, IntoElement, ParentElement, RenderOnce, Styled, WindowContext,
};
use gpux_css::box_shadow::box_shadows_str;
use once_cell::sync::OnceCell;
use smallvec::SmallVec;

#[derive(IntoElement)]
pub struct Facebook {
    pub id: ElementId,
}

impl Facebook {
    pub fn new(id: impl Into<ElementId>) -> Self {
        Self { id: id.into() }
    }
}

static BOX_SHADOWS: OnceCell<SmallVec<[BoxShadow; 2]>> = OnceCell::new();

impl RenderOnce for Facebook {
    fn render(self, _cx: &mut WindowContext) -> impl IntoElement {
        let box_shadows = BOX_SHADOWS.get_or_init(|| {
            let color = "#4566ae";
            box_shadows_str(
                format!(
                    r#"
                    2px 1px {color},
                    3px 1px {color},
                    4px 1px {color},
                    5px 1px {color},
                    6px 1px {color},
                    7px 1px {color},
                    8px 1px {color},
                    9px 1px {color},
                    10px 1px {color},
                    11px 1px {color},
                    12px 1px {color},
                    13px 1px {color},
                    14px 1px {color},
                    15px 1px {color},
                    1px 2px {color},
                    2px 2px {color},
                    3px 2px {color},
                    4px 2px {color},
                    5px 2px {color},
                    6px 2px {color},
                    7px 2px {color},
                    8px 2px {color},
                    9px 2px {color},
                    10px 2px {color},
                    11px 2px #fff,
                    12px 2px #fff,
                    13px 2px #fff,
                    14px 2px #fff,
                    15px 2px {color},
                    16px 2px {color},
                    1px 3px {color},
                    2px 3px {color},
                    3px 3px {color},
                    4px 3px {color},
                    5px 3px {color},
                    6px 3px {color},
                    7px 3px {color},
                    8px 3px {color},
                    9px 3px {color},
                    10px 3px #fff,
                    11px 3px #fff,
                    12px 3px #fff,
                    13px 3px #fff,
                    14px 3px #fff,
                    15px 3px {color},
                    16px 3px {color},
                    1px 4px {color},
                    2px 4px {color},
                    3px 4px {color},
                    4px 4px {color},
                    5px 4px {color},
                    6px 4px {color},
                    7px 4px {color},
                    8px 4px {color},
                    9px 4px #fff,
                    10px 4px #fff,
                    11px 4px #fff,
                    12px 4px #fff,
                    13px 4px #fff,
                    14px 4px #fff,
                    15px 4px {color},
                    16px 4px {color},
                    1px 5px {color},
                    2px 5px {color},
                    3px 5px {color},
                    4px 5px {color},
                    5px 5px {color},
                    6px 5px {color},
                    7px 5px {color},
                    8px 5px {color},
                    9px 5px #fff,
                    10px 5px #fff,
                    11px 5px #fff,
                    12px 5px {color},
                    13px 5px {color},
                    14px 5px {color},
                    15px 5px {color},
                    16px 5px {color},
                    1px 6px {color},
                    2px 6px {color},
                    3px 6px {color},
                    4px 6px {color},
                    5px 6px {color},
                    6px 6px {color},
                    7px 6px {color},
                    8px 6px {color},
                    9px 6px #fff,
                    10px 6px #fff,
                    11px 6px #fff,
                    12px 6px {color},
                    13px 6px {color},
                    14px 6px {color},
                    15px 6px {color},
                    16px 6px {color},
                    1px 7px {color},
                    2px 7px {color},
                    3px 7px {color},
                    4px 7px {color},
                    5px 7px {color},
                    6px 7px {color},
                    7px 7px {color},
                    8px 7px {color},
                    9px 7px #fff,
                    10px 7px #fff,
                    11px 7px #fff,
                    12px 7px {color},
                    13px 7px {color},
                    14px 7px {color},
                    15px 7px {color},
                    16px 7px {color},
                    1px 8px {color},
                    2px 8px {color},
                    3px 8px {color},
                    4px 8px {color},
                    5px 8px {color},
                    6px 8px #fff,
                    7px 8px #fff,
                    8px 8px #fff,
                    9px 8px #fff,
                    10px 8px #fff,
                    11px 8px #fff,
                    12px 8px #fff,
                    13px 8px #fff,
                    14px 8px #fff,
                    15px 8px {color},
                    16px 8px {color},
                    1px 9px {color},
                    2px 9px {color},
                    3px 9px {color},
                    4px 9px {color},
                    5px 9px {color},
                    6px 9px #fff,
                    7px 9px #fff,
                    8px 9px #fff,
                    9px 9px #fff,
                    10px 9px #fff,
                    11px 9px #fff,
                    12px 9px #fff,
                    13px 9px #fff,
                    14px 9px #fff,
                    15px 9px {color},
                    16px 9px {color},
                    1px 10px {color},
                    2px 10px {color},
                    3px 10px {color},
                    4px 10px {color},
                    5px 10px {color},
                    6px 10px #fff,
                    7px 10px #fff,
                    8px 10px #fff,
                    9px 10px #fff,
                    10px 10px #fff,
                    11px 10px #fff,
                    12px 10px #fff,
                    13px 10px #fff,
                    14px 10px #fff,
                    15px 10px {color},
                    16px 10px {color},
                    1px 11px {color},
                    2px 11px {color},
                    3px 11px {color},
                    4px 11px {color},
                    5px 11px {color},
                    6px 11px {color},
                    7px 11px {color},
                    8px 11px {color},
                    9px 11px #fff,
                    10px 11px #fff,
                    11px 11px #fff,
                    12px 11px {color},
                    13px 11px {color},
                    14px 11px {color},
                    15px 11px {color},
                    16px 11px {color},
                    1px 12px {color},
                    2px 12px {color},
                    3px 12px {color},
                    4px 12px {color},
                    5px 12px {color},
                    6px 12px {color},
                    7px 12px {color},
                    8px 12px {color},
                    9px 12px #fff,
                    10px 12px #fff,
                    11px 12px #fff,
                    12px 12px {color},
                    13px 12px {color},
                    14px 12px {color},
                    15px 12px {color},
                    16px 12px {color},
                    1px 13px {color},
                    2px 13px {color},
                    3px 13px {color},
                    4px 13px {color},
                    5px 13px {color},
                    6px 13px {color},
                    7px 13px {color},
                    8px 13px {color},
                    9px 13px #fff,
                    10px 13px #fff,
                    11px 13px #fff,
                    12px 13px {color},
                    13px 13px {color},
                    14px 13px {color},
                    15px 13px {color},
                    16px 13px {color},
                    1px 14px {color},
                    2px 14px {color},
                    3px 14px {color},
                    4px 14px {color},
                    5px 14px {color},
                    6px 14px {color},
                    7px 14px {color},
                    8px 14px {color},
                    9px 14px #fff,
                    10px 14px #fff,
                    11px 14px #fff,
                    12px 14px {color},
                    13px 14px {color},
                    14px 14px {color},
                    15px 14px {color},
                    16px 14px {color},
                    1px 15px {color},
                    2px 15px {color},
                    3px 15px {color},
                    4px 15px {color},
                    5px 15px {color},
                    6px 15px {color},
                    7px 15px {color},
                    8px 15px {color},
                    9px 15px #fff,
                    10px 15px #fff,
                    11px 15px #fff,
                    12px 15px {color},
                    13px 15px {color},
                    14px 15px {color},
                    15px 15px {color},
                    16px 15px {color},
                    2px 16px {color},
                    3px 16px {color},
                    4px 16px {color},
                    5px 16px {color},
                    6px 16px {color},
                    7px 16px {color},
                    8px 16px {color},
                    9px 16px #fff,
                    10px 16px #fff,
                    11px 16px #fff,
                    12px 16px {color},
                    13px 16px {color},
                    14px 16px {color},
                    15px 16px {color}
                    "#
                )
                .as_str(),
            )
        });

        div()
            .size_4()
            .child(div().size(px(1.)).shadow(box_shadows.clone()))
    }
}
